rabbitmq:
  image: tutum/rabbitmq
  environment:
    - RABBITMQ_PASS=password
  ports:
    - "5672:5672"
    - "15672:15672"

# https://hub.docker.com/r/tutum/rabbitmq/
# curl --user admin:password 127.0.0.1:5672/api/vhosts